name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_apply:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.7
    - run: cd infra && terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'infra'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_giphy_api_key:  ${{ secrets.GIPHY_API_KEY }}
        TF_VAR_aws_region:  us-east-1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build REST API
      run: cd api && python3 -m venv venv_rest && source venv_rest/bin/activate && pip install -r api/requirements.txt && cp -r ./venv_rest/lib/python3.9/site-packages/ ../infra/.temp_rest && cp -r api/* ../infra/.temp_rest

    - name: Build Websocket API
      run: cd api && python3 -m venv venv_ws && source venv_ws/bin/activate && pip install -r websocket/requirements.txt && cp -r ./venv_ws/lib/python3.9/site-packages/ ../infra/.temp_ws && cp -r websocket/* ../infra/.temp_ws

    - name: Terraform Validate
      run: cd infra && terraform init
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Terraform Apply
      run: cd infra && terraform apply --auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'infra'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_giphy_api_key:  ${{ secrets.GIPHY_API_KEY }}
        TF_VAR_aws_region:  us-east-1
