name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2.4.0

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.8.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'infra'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_giphy_api_key:  ${{ secrets.GIPHY_API_KEY }}
        TF_VAR_aws_region:  us-east-1

    - name: Build API
      run: make build

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.8.0

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.8.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'infra'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_giphy_api_key:  ${{ secrets.GIPHY_API_KEY }}
        TF_VAR_aws_region:  us-east-1
