name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v1
    - run: terraform_up
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_giphy_api_key:  ${{ secrets.GIPHY_API_KEY }}
        TF_VAR_aws_region:  us-east-1
