name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.7
    - run: cd infra && terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'infra'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_giphy_api_key:  ${{ secrets.GIPHY_API_KEY }}
        TF_VAR_aws_region:  us-east-1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build API
      run: python3 -m venv venv && source venv/bin/activate && pip install -r api/requirements.txt

    - name: Terraform Validate
      run: cd infra && terraform init

    - name: Terraform Apply
      run: cd infra && terraform apply --auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'infra'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        TF_VAR_aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_giphy_api_key:  ${{ secrets.GIPHY_API_KEY }}
        TF_VAR_aws_region:  us-east-1
